### ISSUE TITLE
Fatal error: Call to undefined function backdrop_bootstrap

### ISSUE THREAD

**Issue by idflorin** [backdrop-contrib/statistics#1]
> Warning: chdir(): Invalid argument (errno 22) in C:\wamp\www\backdropcms\modules\statistics-1.x-1.x\statistics.php on line 13

>  Warning: include_once(/core/includes/bootstrap.inc): failed to open stream: No such file or directory in C:\wamp\www\backdropcms\modules\statistics-1.x-1.x\statistics.php on line 15

> ( ! ) Fatal error: Call to undefined function backdrop_bootstrap() in C:\wamp\www\backdropcms\modules\statistics-1.x-1.x\statistics.php on line 16

**Comment by docwilmot** [comment]
More info?

**Comment by idflorin** [comment]
can't reproduce. close it please
