### ISSUE TITLE
"Use Ajax to increment the counter" doesn't work

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/statistics#15]
In the settings at admin/config/system/statistics, checking the "Use Ajax to increment the counter" box doesn't work; the node counter is no longer incremented when it is checked.

This is because the path to the module in file statistics.php assumes the module is placed at the root of the modules folder, but the Backdrop-recommended file organization is to put it in modules/contrib.

PR to follow.

**Comment by olafgrabienski** [comment]
> the path to the module in file statistics.php assumes the module is placed at the root of the modules folder, but the Backdrop-recommended file organization is to put it in modules/contrib

While the latter might be recommended (source?), I usually don't put modules in subfolders like `modules/contrib`. Does that mean, the Ajax counter wouldn't work for me when I apply the PR?

**Comment by bugfolder** [comment]
Ah, yeah, that's what it means. So I'll work on a better solution that won't depend on the specific location.

**Comment by bugfolder** [comment]
> While the latter might be recommended (source?)

The README file in the modules directory of a fresh download says:

> You may create subdirectories within this directory to organize your added modules. Some common subdirectories include "contrib" for contributed modules, and "custom" for custom modules.

**Comment by bugfolder** [comment]
PR is updated to be location-agnostic (it can be anywhere in the /modules/ hierarchy).

**Comment by olafgrabienski** [comment]
> PR is updated to be location-agnostic (it can be anywhere in the /modules/ hierarchy).

Great, thanks!

Note: I've not tested the PR (not using the module so far, was just stumbling about the issue by accident).
