### ISSUE TITLE
Upgrade from Drupal 7 fails because of wrong database structure

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/statistics#19]
Hi,
when upgrading from Drupal 7 it fails because of the new database structure. The columns weekcount, monthcount and yearcount were missing.

Is it possible to check whether the structure differs and create them if it does so during upgrade?

**Comment by docwilmot** [comment]
This should be fixed by https://github.com/backdrop-contrib/statistics/pull/10

**Comment by djzwerg** [comment]
Yes! Thanks!
