### ISSUE TITLE
Views output is empty

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/statistics#20]
If you want to use the statistics counter within a view (aggregation active to sum all views) you get zero views on all pages and overall.

Edit: tested with PHP 7.3 and 7.4

**Comment by djzwerg** [comment]
Error message:
`Notice: Trying to access array offset on value of type bool in statistics_views_handler_field_totalcount_numeric->render() (line 54 of /mypath/modules/statistics/views/statistics_views_handler_field_totalcount_numeric.inc).`

**Comment by docwilmot** [comment]
Could I get an example of a View that gets this error please?

**Comment by djzwerg** [comment]
Of course @docwilmot. After a few tests I have to clarify that this error occurs only on a D7 upgraded site:

`        "rib_statistiken": {
            "display_title": "Statistiken",
            "display_plugin": "block",
            "display_options": {
                "query": {
                    "type": "views_query",
                    "options": []
                },
                "display_description": "",
                "title": "Statistiken",
                "defaults": {
                    "title": false,
                    "style_plugin": false,
                    "style_options": false,
                    "row_plugin": false,
                    "row_options": false,
                    "footer": false,
                    "group_by": false,
                    "fields": false,
                    "header": false,
                    "filters": false,
                    "filter_groups": false
                },
                "style_plugin": "default",
                "style_options": {
                    "grouping": [],
                    "row_class": "",
                    "default_row_class": 0,
                    "row_class_special": 0
                },
                "row_plugin": "fields",
                "row_options": [],
                "footer": {
                    "area": {
                        "id": "area",
                        "table": "views",
                        "field": "area",
                        "relationship": "none",
                        "group_type": "group",
                        "ui_name": "",
                        "label": "",
                        "empty": 0,
                        "content": "<p>© 2013-[current-date:custom:Y] <a href=\"https://www.halle-im-bild.de\" target=\"_blank\">Halle im Bild</a></p>\r\n",
                        "format": "full_html",
                        "tokenize": 1
                    }
                },
                "group_by": 1,
                "fields": {
                    "title": {
                        "id": "title",
                        "table": "node",
                        "field": "title",
                        "relationship": "none",
                        "group_type": "count_distinct",
                        "ui_name": "",
                        "label": "",
                        "exclude": 1,
                        "alter": {
                            "alter_text": 0,
                            "text": "",
                            "make_link": 0,
                            "path": "",
                            "absolute": 0,
                            "external": 0,
                            "replace_spaces": 0,
                            "path_case": "none",
                            "trim_whitespace": 0,
                            "alt": "",
                            "rel": "",
                            "link_class": "",
                            "prefix": "",
                            "suffix": "",
                            "target": "",
                            "nl2br": 0,
                            "max_length": "",
                            "word_boundary": 0,
                            "ellipsis": 0,
                            "more_link": 0,
                            "more_link_text": "",
                            "more_link_path": "",
                            "strip_tags": 0,
                            "trim": 0,
                            "preserve_tags": "",
                            "html": 0
                        },
                        "element_type": "",
                        "element_class": "",
                        "element_label_type": "",
                        "element_label_class": "",
                        "element_label_colon": false,
                        "element_wrapper_type": "",
                        "element_wrapper_class": "",
                        "element_default_classes": 1,
                        "empty": "",
                        "hide_empty": 0,
                        "empty_zero": 0,
                        "hide_alter_empty": 1,
                        "set_precision": false,
                        "precision": 0,
                        "decimal": ".",
                        "separator": ".",
                        "format_plural": 0,
                        "format_plural_singular": "1",
                        "format_plural_plural": "@count",
                        "prefix": "",
                        "suffix": "",
                        "link_to_node": 1
                    },
                    "field_standort": {
                        "id": "field_standort",
                        "table": "field_data_field_standort",
                        "field": "field_standort",
                        "relationship": "none",
                        "group_type": "count_distinct",
                        "ui_name": "",
                        "label": "",
                        "exclude": 1,
                        "alter": {
                            "alter_text": 0,
                            "text": "",
                            "make_link": 0,
                            "path": "",
                            "absolute": 0,
                            "external": 0,
                            "replace_spaces": 0,
                            "path_case": "none",
                            "trim_whitespace": 0,
                            "alt": "",
                            "rel": "",
                            "link_class": "",
                            "prefix": "",
                            "suffix": "",
                            "target": "",
                            "nl2br": 0,
                            "max_length": "",
                            "word_boundary": 1,
                            "ellipsis": 1,
                            "more_link": 0,
                            "more_link_text": "",
                            "more_link_path": "",
                            "strip_tags": 0,
                            "trim": 0,
                            "preserve_tags": "",
                            "html": 0
                        },
                        "element_type": "",
                        "element_class": "",
                        "element_label_type": "",
                        "element_label_class": "",
                        "element_label_colon": false,
                        "element_wrapper_type": "",
                        "element_wrapper_class": "",
                        "element_default_classes": 1,
                        "empty": "",
                        "hide_empty": 0,
                        "empty_zero": 0,
                        "hide_alter_empty": 1,
                        "set_precision": false,
                        "precision": 0,
                        "decimal": ".",
                        "separator": ".",
                        "format_plural": 0,
                        "format_plural_singular": "1",
                        "format_plural_plural": "@count",
                        "prefix": "",
                        "suffix": "",
                        "click_sort_column": "",
                        "type": "geofield_wkt",
                        "settings": [],
                        "group_column": "entity_id",
                        "group_columns": [],
                        "group_rows": true,
                        "delta_limit": "all",
                        "delta_offset": 0,
                        "delta_reversed": false,
                        "delta_first_last": false,
                        "multi_type": "separator",
                        "field_api_classes": false
                    },
                    "delta": {
                        "id": "delta",
                        "table": "field_data_field_galerie",
                        "field": "delta",
                        "relationship": "none",
                        "group_type": "count",
                        "ui_name": "",
                        "label": "",
                        "exclude": 1,
                        "alter": {
                            "alter_text": 0,
                            "text": "",
                            "make_link": 0,
                            "path": "",
                            "absolute": 0,
                            "external": 0,
                            "replace_spaces": 0,
                            "path_case": "none",
                            "trim_whitespace": 0,
                            "alt": "",
                            "rel": "",
                            "link_class": "",
                            "prefix": "",
                            "suffix": "",
                            "target": "",
                            "nl2br": 0,
                            "max_length": "",
                            "word_boundary": 1,
                            "ellipsis": 1,
                            "more_link": 0,
                            "more_link_text": "",
                            "more_link_path": "",
                            "strip_tags": 0,
                            "trim": 0,
                            "preserve_tags": "",
                            "html": 0
                        },
                        "element_type": "",
                        "element_class": "",
                        "element_label_type": "",
                        "element_label_class": "",
                        "element_label_colon": false,
                        "element_wrapper_type": "",
                        "element_wrapper_class": "",
                        "element_default_classes": 1,
                        "empty": "",
                        "hide_empty": 0,
                        "empty_zero": 0,
                        "hide_alter_empty": 1,
                        "set_precision": false,
                        "precision": 0,
                        "decimal": ".",
                        "separator": ".",
                        "format_plural": 0,
                        "format_plural_singular": "1",
                        "format_plural_plural": "@count",
                        "prefix": "",
                        "suffix": ""
                    },
                    "field_kuenstler": {
                        "id": "field_kuenstler",
                        "table": "field_data_field_kuenstler",
                        "field": "field_kuenstler",
                        "relationship": "none",
                        "group_type": "count_distinct",
                        "ui_name": "",
                        "label": "",
                        "exclude": 1,
                        "alter": {
                            "alter_text": 0,
                            "text": "",
                            "make_link": 0,
                            "path": "",
                            "absolute": 0,
                            "external": 0,
                            "replace_spaces": 0,
                            "path_case": "none",
                            "trim_whitespace": 0,
                            "alt": "",
                            "rel": "",
                            "link_class": "",
                            "prefix": "",
                            "suffix": "",
                            "target": "",
                            "nl2br": 0,
                            "max_length": "",
                            "word_boundary": 1,
                            "ellipsis": 1,
                            "more_link": 0,
                            "more_link_text": "",
                            "more_link_path": "",
                            "strip_tags": 0,
                            "trim": 0,
                            "preserve_tags": "",
                            "html": 0
                        },
                        "element_type": "",
                        "element_class": "",
                        "element_label_type": "",
                        "element_label_class": "",
                        "element_label_colon": false,
                        "element_wrapper_type": "",
                        "element_wrapper_class": "",
                        "element_default_classes": 1,
                        "empty": "",
                        "hide_empty": 0,
                        "empty_zero": 0,
                        "hide_alter_empty": 1,
                        "set_precision": false,
                        "precision": 0,
                        "decimal": ".",
                        "separator": ".",
                        "format_plural": 0,
                        "format_plural_singular": "1",
                        "format_plural_plural": "@count",
                        "prefix": "",
                        "suffix": "",
                        "click_sort_column": "tid",
                        "type": "taxonomy_term_reference_link",
                        "settings": [],
                        "group_column": "tid",
                        "group_columns": [],
                        "group_rows": true,
                        "delta_limit": "all",
                        "delta_offset": 0,
                        "delta_reversed": false,
                        "delta_first_last": false,
                        "multi_type": "separator",
                        "field_api_classes": false
                    },
                    "nothing": {
                        "id": "nothing",
                        "table": "views",
                        "field": "nothing",
                        "relationship": "none",
                        "group_type": "group",
                        "ui_name": "",
                        "label": "",
                        "exclude": 0,
                        "alter": {
                            "alter_text": true,
                            "text": "<p style=\"text-align:center;\" class=\"hib-footerstatistik\"> [delta] Fotos in <a href=\"/fotos\">[field_standort] Objekten</a> • <a href=\"/kuenstler\">[field_kuenstler] Künstler</a>",
                            "make_link": 0,
                            "path": "",
                            "absolute": 0,
                            "external": 0,
                            "replace_spaces": 0,
                            "path_case": "none",
                            "trim_whitespace": 0,
                            "alt": "",
                            "rel": "",
                            "link_class": "",
                            "prefix": "",
                            "suffix": "",
                            "target": "",
                            "nl2br": 0,
                            "max_length": "",
                            "word_boundary": 1,
                            "ellipsis": 1,
                            "more_link": 0,
                            "more_link_text": "",
                            "more_link_path": "",
                            "strip_tags": 0,
                            "trim": 0,
                            "preserve_tags": "",
                            "html": 0
                        },
                        "element_type": "",
                        "element_class": "",
                        "element_label_type": "",
                        "element_label_class": "",
                        "element_label_colon": false,
                        "element_wrapper_type": "",
                        "element_wrapper_class": "",
                        "element_default_classes": 1,
                        "empty": "",
                        "hide_empty": 0,
                        "empty_zero": 0,
                        "hide_alter_empty": 0
                    },
                    "totalcount": {
                        "id": "totalcount",
                        "table": "node",
                        "field": "totalcount",
                        "relationship": "none",
                        "group_type": "sum",
                        "ui_name": "",
                        "label": "Total pageviews",
                        "exclude": 0,
                        "alter": {
                            "alter_text": 0,
                            "text": "",
                            "make_link": 0,
                            "path": "",
                            "absolute": 0,
                            "external": 0,
                            "replace_spaces": 0,
                            "path_case": "none",
                            "trim_whitespace": 0,
                            "alt": "",
                            "rel": "",
                            "link_class": "",
                            "prefix": "",
                            "suffix": "",
                            "target": "",
                            "nl2br": 0,
                            "max_length": "",
                            "word_boundary": 1,
                            "ellipsis": 1,
                            "more_link": 0,
                            "more_link_text": "",
                            "more_link_path": "",
                            "strip_tags": 0,
                            "trim": 0,
                            "preserve_tags": "",
                            "html": 0
                        },
                        "element_type": "",
                        "element_class": "",
                        "element_label_type": "",
                        "element_label_class": "",
                        "element_label_colon": 1,
                        "element_wrapper_type": "",
                        "element_wrapper_class": "",
                        "element_default_classes": 1,
                        "empty": "",
                        "hide_empty": 0,
                        "empty_zero": 0,
                        "hide_alter_empty": 1,
                        "set_precision": false,
                        "precision": 0,
                        "decimal": ".",
                        "separator": ".",
                        "format_plural": false,
                        "format_plural_singular": "1",
                        "format_plural_plural": "@count",
                        "prefix": "",
                        "suffix": ""
                    }
                },
                "header": [],
                "filters": {
                    "status": {
                        "id": "status",
                        "table": "node",
                        "field": "status",
                        "relationship": "none",
                        "group_type": "group",
                        "ui_name": "",
                        "operator": "=",
                        "value": "1",
                        "group": 1,
                        "exposed": false,
                        "expose": {
                            "operator_id": "",
                            "label": "Veröffentlicht",
                            "description": null,
                            "use_operator": false,
                            "operator": "status_op",
                            "identifier": "status",
                            "required": true,
                            "remember": false,
                            "multiple": false,
                            "remember_roles": {
                                "authenticated": "authenticated"
                            }
                        },
                        "is_grouped": false,
                        "group_info": {
                            "label": "",
                            "description": "",
                            "identifier": "",
                            "optional": true,
                            "widget": "select",
                            "multiple": false,
                            "remember": 0,
                            "default_group": "All",
                            "default_group_multiple": [],
                            "group_items": []
                        }
                    }
                },
                "filter_groups": {
                    "operator": "AND",
                    "groups": {
                        "1": "AND"
                    }
                }
            }
        },`

**Comment by djzwerg** [comment]
On a fresh BD site this works. The database table structure looks to be the same, the code is the same. I can't figure out why this doesn't work on the migrated site.

**Comment by djzwerg** [comment]
The `totalcount` aggregation is set to SUM[totalcount]

**Comment by djzwerg** [comment]
Well this would be fixed by https://github.com/backdrop-contrib/statistics/pull/10 too. Thanks!

**Comment by djzwerg** [comment]
I'm sorry I have to reopen this issue. I did a test on several sites and after the last update it works on 1 of 6.

**Comment by djzwerg** [comment]
The fields:
![grafik](https://user-images.githubusercontent.com/49948628/160713185-979037cc-ff5d-46cf-bd37-d958ec4fb16c.png)

Other settings:
![grafik](https://user-images.githubusercontent.com/49948628/160713268-b1226ede-7a0a-43f5-a566-7d11a9ad4aa2.png)

Working output:
![grafik](https://user-images.githubusercontent.com/49948628/160713314-c6c50da8-d618-4cb3-8485-2e52e6c53473.png)

I made a copy of the site's node_counter table to the others but the output of the other sites is still 0.

**Comment by docwilmot** [comment]
@djzwerg I think you only posted a section of the View. Could you post the whole json file please?

**Comment by djzwerg** [comment]
@docwilmot sorry for the delay but the last weeks there were no time for working on Backdrop sites.

After a few tests I did find out that this issue is a duplicate of https://github.com/backdrop-contrib/statistics/issues/4. It works without site aggregation.

So I will close this one. Thanks for your work!
