### ISSUE TITLE
Day's top is displayed 4 times in "Popular content" block config

### ISSUE THREAD

**Issue by pabloslab** [backdrop-contrib/statistics#21]
In the "Popular content" block configuration, the _day's top_ is displayed 4 times. Actual values to setup are for day, week, month and year.

![StatsBlock](https://user-images.githubusercontent.com/101482586/159078857-686a7cd2-ce92-47a7-87a5-65496109468a.PNG)

**Comment by pabloslab** [comment]
PR #22 worked in my tests

**Comment by docwilmot** [comment]
Fixed, thanks
